"""empty message

Revision ID: 016e39ed942f
Revises: 818f71e2180c
Create Date: 2019-09-30 14:22:09.948505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016e39ed942f'
down_revision = '818f71e2180c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE todos SET completed = FALSE where completed IS NULL;')

    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
